version: "3.8"
services:
  deno:
    build: 
      context: .
      dockerfile: Dockerfile.deno
    volumes:
      - ./app:/app
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      MONGODB_URI: mongodb://mongodb:27017/creda
    command: ["run", "--allow-net", "--allow-env", "/main.ts"]

  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: borjovsky
      MONGO_INITDB_ROOT_PASSWORD: cd0841
    volumes:
      - ./mongo-data:/data/db
